--Tarefa: PEDIDO V

--Pesquisa exemplo de informações
SELECT TOP 10 PEDIDO_ID, * FROM TB_TRANSPORTADORA
WHERE
    ISNULL(PEDIDO_ID,0) <> 0
    
    SELECT TOP 1 ATENDIDO, * FROM TB_PEDIDO
    WHERE PEDIDO_ID = 2
    
    SELECT * FROM TB_PESSOATRANSPORTADORAPRAZOENTREGA
    WHERE
        PESSOA_ID = 3917
        AND CIDADE_DESTINO_ID = 6015
        AND CIDADE_ORIGEM_ID = 9250
        
-- SELECTS CORRETO
SELECT TOP 10 EMPRESA_ID, * FROM TB_PEDIDO
WHERE
    ISNULL(PEDIDO_ID,0) <> 0
    
SELECT TOP 10 CIDADE_ID, * FROM TB_EMPRESA

SELECT TOP 10 ENDERECO_PRINCIPAL_ID * FROM TB_PESSOAS P
INNER JOIN TB_PESSOASENDERECO PE ON P.PESSOA_ID = PE.PESSOA_ID

SELECT TOP 10 PRAZO_DIAS * FROM TB_PESSOATRANSPORTADORAPRAZOENTREGA PT
WHERE
		ISNULL(PEDIDO_ID,0) <> 0
AND PT.CIDADE_ORIGEM_ID <> 0
AND PT.CIDADE_DESTINO_ID <> 0 

--SELECTS
--- Este select, apresente o nome da empresa, a cidade da empresa.
--- Com base em um pedido.

SELECT TOP 1 
    P.PEDIDO_ID, 
    P.EMPRESA_ID AS EMPRESA_ID_PEDIDO,
    E.EMPRESA_ID AS EMPRESA_ID_EMPRESA,
    E.CIDADE_ID AS CIDADE_EMPRESA,
    E.NOME AS NOME_EMPRESA,
    E.NOME_SISTEMA AS NOME_SISTEMA_EMPRESA,
    C.NOME AS NOME_CIDADE
FROM TB_PEDIDO AS P
INNER JOIN DBO.TB_EMPRESA E with(READUNCOMMITTED) ON E.EMPRESA_ID = P.EMPRESA_ID AND E.STATUS <> 0
LEFT JOIN TB_PAISESTADOCIDADE AS C ON C.CIDADE_ID = E.CIDADE_ID AND C.STATUS <> 0
WHERE P.STATUS <> 0
AND ISNULL(P.EMPRESA_ID,0) <> 0
AND ISNULL(P.EMPRESA_ID,0) = 2


--------------------------

SELECT TOP 1 
    P.PEDIDO_ID, 
    P.EMPRESA_ID AS EMPRESA_ID_PEDIDO,
    E.EMPRESA_ID AS EMPRESA_ID_EMPRESA,
    E.CIDADE_ID AS CIDADE_EMPRESA,
    E.NOME AS NOME_EMPRESA,
    E.NOME_SISTEMA AS NOME_SISTEMA_EMPRESA,
    C.NOME AS NOME_CIDADE,
    P.PESSOA_CLIENTE_ID AS CLIENTE_ID,
    EP.CIDADE_ID, 
    EP.CIDADE AS NOME_CIDADE_CLIENTE
FROM TB_PEDIDO AS P
INNER JOIN DBO.TB_EMPRESA E with(READUNCOMMITTED) ON E.EMPRESA_ID = P.EMPRESA_ID AND E.STATUS <> 0
LEFT JOIN TB_PAISESTADOCIDADE AS C ON C.CIDADE_ID = E.CIDADE_ID AND C.STATUS <> 0
LEFT JOIN VW_PESSOAENDERECOPRINCIPAL AS EP ON EP.PESSOA_ID =  P.PESSOA_CLIENTE_ID AND EP.STATUS <> 0
WHERE P.STATUS <> 0
AND ISNULL(P.EMPRESA_ID,0) <> 0
AND ISNULL(P.EMPRESA_ID,0) = 2
AND P.PEDIDO_ID = 15572

-------------------------

SELECT TOP 1
    P.PRAZO_ENTREGA,
    PE.PRAZOENTREGA_ID, --VAI INDICAR QUAL REGISTRO IRÁ SER ATUALIZADO
    E.CIDADE_ID AS CIDADE_EMPRESA, -- CIDADE_ORGEM
    EP.CIDADE_ID AS CIDADE_CLIENTE -- CIDADE DESTINO
FROM TB_PEDIDO AS P
INNER JOIN DBO.TB_EMPRESA E with(READUNCOMMITTED) ON E.EMPRESA_ID = P.EMPRESA_ID AND E.STATUS <> 0
LEFT JOIN TB_PAISESTADOCIDADE AS C ON C.CIDADE_ID = E.CIDADE_ID AND C.STATUS <> 0
LEFT JOIN VW_PESSOAENDERECOPRINCIPAL AS EP ON EP.PESSOA_ID =  P.PESSOA_CLIENTE_ID AND EP.STATUS <> 0
LEFT JOIN TB_PESSOATRANSPORTADORAPRAZOENTREGA AS PE ON PE.CIDADE_DESTINO_ID = E.CIDADE_ID 
AND PE.CIDADE_ORIGEM_ID = EP.CIDADE_ID AND PE.STATUS <> 0
WHERE P.STATUS <> 0
AND ISNULL(P.EMPRESA_ID,0) <> 0
AND ISNULL(P.EMPRESA_ID,0) = 2
AND P.PEDIDO_ID = 15572

-------------------


DECLARE @PRAZODIAS AS INT
SELECT
    P.PEDIDO_ID,
    PE.PRAZO_DIAS, -- ESTE CAMPO SERÁ UTILIZADO PARA O UDATE NA TB_PEDIDO
    PE.PRAZOENTREGA_ID, --VAI INDICAR QUAL REGISTRO IRÁ SER ATUALIZADO
    E.CIDADE_ID AS CIDADE_EMPRESA, -- CIDADE_ORIGEM
    EP.CIDADE_ID AS CIDADE_CLIENTE -- CIDADE DESTINO
FROM TB_PEDIDO AS P
INNER JOIN DBO.TB_EMPRESA E with(READUNCOMMITTED) ON E.EMPRESA_ID = P.EMPRESA_ID AND E.STATUS <> 0
LEFT JOIN TB_PAISESTADOCIDADE AS C ON C.CIDADE_ID = E.CIDADE_ID AND C.STATUS <> 0
LEFT JOIN VW_PESSOAENDERECOPRINCIPAL AS EP ON EP.PESSOA_ID =  P.PESSOA_CLIENTE_ID AND EP.STATUS <> 0
LEFT JOIN TB_PESSOATRANSPORTADORAPRAZOENTREGA AS PE ON 
    PE.CIDADE_DESTINO_ID = EP.CIDADE_ID
AND PE.CIDADE_ORIGEM_ID = E.CIDADE_ID AND PE.STATUS <> 0
WHERE P.STATUS <> 0
AND ISNULL(P.EMPRESA_ID,0) <> 0
AND ISNULL(P.EMPRESA_ID,0) = 2
AND P.PEDIDO_ID = 15572

SELECT PRAZO_ENTREGA FROM TB_PEDIDO
WHERE STATUS <> 0 AND PEDIDO_ID = 15572