--Tarefa: Produto Inmetro 2

@DATA_EMISSAOASSMALLDATETIME,
@DATA_VALIDADEASSMALLDATETIME,
@NUMERO_CERTIFICADOASNVARCHAR(500),
@NUMERO_REGISTROASNVARCHAR(500),
@PRODUTO_IDASBIGINT,
@USUARIO_IDASBIGINT
AS
BEGINDECLARE@RESULTADOASNVARCHAR(100) ='Erro ao importar o CSV'DECLARE@REGISTROJACADASTRADOASBIGINTDECLARE@PRODUTOIDVALIDOASBIGINT

SELECT@REGISTROJACADASTRADO =ISNULL(PI.INMETRO_ID,0)
FROM TB_PRODUTOINMETROASPIWHEREPI.STATUS <>0ANDPI.NUMERO_REGISTRO =@NUMERO_REGISTRO

SELECT@PRODUTOIDVALIDO =ISNULL(P.PRODUTO_ID,0)
FROM TB_PRODUTOAS P
WHERE P.STATUS <>0AND P.PRODUTO_ID =@PRODUTO_IDIFISNULL(@DATA_EMISSAO,'') <>''ANDISNULL(@DATA_VALIDADE,'') <>''ANDISNULL(@NUMERO_CERTIFICADO,'') <>''ANDISNULL(@NUMERO_REGISTRO,'') <>''ANDISNULL(@REGISTROJACADASTRADO,0) =0ANDISNULL(@PRODUTOIDVALIDO,0) <>0BEGININSERTINTO [TB_PRODUTOINMETRO]
        (
         [DATA_EMISSAO]
        ,[DATA_VALIDADE]
        ,[NUMERO_CERTIFICADO]
        ,[NUMERO_REGISTRO]
        ,[PRODUTO_ID]
        ,[ACAO_ID]
        ,[STATUS]
        ,[USER_ID]
        ,[ULT_ALT]
        ,[ULT_USER_ID]
        )
VALUES
        (
@DATA_EMISSAO
        ,@DATA_VALIDADE
        ,@NUMERO_CERTIFICADO
        ,@NUMERO_REGISTRO
        ,@PRODUTO_ID
        ,1
        ,1
        ,@USUARIO_ID
        ,GETDATE()
        ,@USUARIO_ID
        )

SET@RESULTADO ='Importacao do CSV realizada com sucesso'END

ELSEBEGINIFISNULL(@DATA_EMISSAO,'') =''ORISNULL(@DATA_VALIDADE,'') =''ORISNULL(@NUMERO_CERTIFICADO,'') =''ORISNULL(@NUMERO_REGISTRO,'') =''BEGINSET@RESULTADO ='Confira os campos obrigatorios'END

IFISNULL(@REGISTROJACADASTRADO,0) <>0BEGINSET@RESULTADO ='Esse numero de registro ja esta cadastrado no sistema'END

IFISNULL(@PRODUTOIDVALIDO,0) =0BEGINSET@PRODUTOIDVALIDO ='Produto invalido ou nao existe'ENDEND

SELECT@RESULTADOAS RESULTADO
END