--Tarefa: CADASTRO>FISCAL>NATUREZA DA OPERAÇÃO	NATUREZA AUTOMÁTICACADASTRO>FISCAL>NATUREZA DA OPERAÇÃO - NATUREZA AUTOMÁTICA

--registros duplicados
SELECT COUNT(*) AS REGISTROS_DUPLICADOS
FROM TB_NATUREZAOPERACAO
WHERE STATUS <> 0
AND TIPO = 'BONIFICAÇÃO'
AND BRINDE = 1;

